version: "3.9"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    container_name: backend
    env_file:
      - .env
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./backend/app/src:/app/src
    depends_on:
      - postgres

  parser:
    build: ./parser
    restart: unless-stopped
    container_name: parser
    env_file:
      - .env
    ports:
      - "127.0.0.1:3456:3456"
    volumes:
      - ./parser/app/src:/app/src
      - ./parser/app/storage:/app/storage
    depends_on:
      - postgres
      - backend

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_backend
    command: tunnel --url http://backend:3000 --protocol http2
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data: